# Generated by Django 6.1.1 on 2026-10-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='best_algorithm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='expected_answer',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='challenge',
            name='input_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='challenge',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='challenge',
            name='topic',
            field=models.CharField(default='sorting', max_length=100),
        ),
    ]
